### ISSUE TITLE
Set "Board" page to be the home page.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog_web#10]
As a user, I'd like to set "Board" page to be the home page, so that I can check my log summary quickly, thanks.

**Comment by Nightlord851108** [comment]
Please do not report an issue with the user story format.

It's just weird.

**Comment by Nightlord851108** [comment]
We'll discuss about the UX, again.

**Comment by ssl1321ois** [comment]
@james-jhang , we may add a tutorial button in welcome page. Also, we already have board button in the sidebar is convenient enough, thank you.
