### ISSUE TITLE
Cannot log in Timelog.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog_web#15]
Cannot log in the Timelog. After login, it redirects to the login page immediately.
![cannotlogintimelog](https://user-images.githubusercontent.com/20788456/89145729-4350f580-d584-11ea-9ba1-2c4b47013571.gif)

Console log:
![image](https://user-images.githubusercontent.com/20788456/89145756-5663c580-d584-11ea-903e-1eb48769aa1a.png)

Network:
[HAR file](https://drive.google.com/file/d/1tvPnlzLmbGltimxv-U4ZA4i1bjpVNql_/view?usp=sharing)
![image](https://user-images.githubusercontent.com/20788456/89145799-6da2b300-d584-11ea-8d96-1e52ae66ca7c.png)

**Comment by james-jhang** [comment]
We found the solution but don't know the reason.
The bug happens when I use this URL to open the Timelog: `https://ssl-timelog.csie.ntut.edu.tw/#/board`. But the bug doesn't happen when I use this URL: "ssl-timelog.csie.ntut.edu.tw".

**Comment by ssl1321ois** [comment]
Please use the URL without hash router 👍
