### ISSUE TITLE
In "History" page, sort the logs in ascending order by default.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog_web#8]
As a user, I'd like to see my logs in ascending order by default, so that I can check logs easier, thanks.

**Comment by Nightlord851108** [comment]
Please do not report an issue with user story format.

It's just weird.

**Comment by Nightlord851108** [comment]
@james-jhang, please specify ascending by what, since we get several attributes for the history page.

**Comment by ssl1321ois** [comment]
@james-jhang , we have already fixed it, thank you
